In [3]:
import numpy as np # as --> allias

###  Numpy arrays
* vector.
* matrices.
* tensors

#### Creating numpy array from list:

In [20]:
my_lst = [1,2,3,4]
type(my_lst)

list

In [21]:
my_mat = np.array(my_lst)

In [22]:
type(my_mat)

numpy.ndarray

In [23]:
my_mat[0]

1

In [24]:
lst_2D = [[1,2],[3,4],[4,8]]

In [25]:
len(lst_2D)

3

In [26]:
lst_2D[1][1]

4

In [27]:
arr_2D = np.array(lst_2D)

In [28]:
type(arr_2D)

numpy.ndarray

In [29]:
arr_2D[1]

array([3, 4])

In [30]:
len(arr_2D)

3

In [31]:
arr_2D

array([[1, 2],
       [3, 4],
       [4, 8]])

In [32]:
arr_2D.shape


(3, 2)

#### Creating numpy array using built in methods.

In [33]:
# arrange: (returns evenly space values )

In [34]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1)

array([0])

In [39]:
# zeros and ones:


In [40]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
#linspace 
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [50]:
#linspace 

np.linspace(1,2)  # default is 50.

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [52]:
# eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.diag([1,1,3])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

#### Generating the random number: 

In [55]:
np.random.randint(1,5) # generate a random integer

4

In [58]:
np.random.randint(1,5,10) # 10 numbers between 1 and 5

array([2, 2, 1, 4, 2, 4, 3, 4, 3, 2])

In [63]:
np.random.randint(1,5,(2,4)) # Two dimensional array:

array([[2, 4, 2, 3],
       [4, 2, 4, 2]])

In [72]:
# seed:
np.random.seed(90)
np.random.randint(1,100,(3,5)) 

array([[92, 30, 32, 68, 40],
       [69, 59, 38, 19, 75],
       [97, 52, 31, 81, 19]])

In [74]:
#randn  # return samples from std normal dist with std = 1. 

In [75]:
np.random.randn(10)

array([-0.84397613,  0.35519384, -1.8939764 ,  1.31099142, -0.28477763,
       -1.21583941, -0.13927516,  0.30593842, -1.30747206, -1.59799603])

In [76]:
np.random.randn(10,10)

array([[ 0.39615537,  0.02756923, -0.40808841,  0.05363833, -1.23713899,
        -0.24855747,  1.31903477,  0.75333725, -0.36290984, -0.4707278 ],
       [-0.15362189,  0.47743601, -1.38034406,  0.86784717, -0.690013  ,
        -0.016771  , -0.33308236,  0.4052747 ,  0.1587977 ,  0.54609483],
       [-1.28634236,  1.05210807, -0.28166   , -0.77186881, -0.44584854,
         0.27078563, -0.63360577, -0.127756  , -0.40184223,  1.05479776],
       [ 0.11090149,  1.63426822,  1.06638374,  1.12163716, -0.22362208,
         0.35298048,  2.1018495 ,  0.03704441, -0.73592965,  0.28551001],
       [-0.85587476, -0.02427242, -0.31296736, -0.78847065, -0.64954285,
        -1.20821608,  0.55860041,  1.06631083, -0.06817771, -1.51931269],
       [-1.37666573,  1.30191393,  1.09346498, -0.38968152, -1.13483907,
        -0.37905671,  1.08314459,  0.12513826, -1.31464399,  0.34540714],
       [-0.17685081, -0.33466503,  0.33977543, -0.782833  , -1.20654438,
         0.49105436,  0.46809773,  1.28403841

In [79]:
np.random.randn(3,2,3)

array([[[-2.85343024, -1.39525402, -0.99800344],
        [-0.20958023, -0.47354869, -0.7297913 ]],

       [[-1.44949209, -0.79612452,  1.39663448],
        [ 1.15909541,  0.26013803, -0.57752567]],

       [[-0.71319358,  0.04647999,  0.00985634],
        [ 0.4011719 , -0.6005746 , -0.04281438]]])

### Arrays attributes and method:

In [83]:
arr = np.arange(25)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [87]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
arr.reshape(5,5)[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [91]:
arr.shape  # shape is an attribute. 

(25,)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
arr.reshape(1,25) # now it is two D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [100]:
np.random.seed(90)
demo_array = np.random.randint(1,100,15)

In [101]:
demo_array

array([92, 30, 32, 68, 40, 69, 59, 38, 19, 75, 97, 52, 31, 81, 19])

In [109]:
demo_array.shape # this is one dime

(1, 15)

In [110]:
np.random.seed(90)
demo_array = np.random.randint(1,100,(1,15))

In [111]:
demo_array

array([[92, 30, 32, 68, 40, 69, 59, 38, 19, 75, 97, 52, 31, 81, 19]])

In [112]:
demo_array.shape # This is two dimension

(1, 15)

In [113]:
np.random.seed(90)
demo_array = np.random.randint(1,100,(15,1))

In [114]:
demo_array

array([[92],
       [30],
       [32],
       [68],
       [40],
       [69],
       [59],
       [38],
       [19],
       [75],
       [97],
       [52],
       [31],
       [81],
       [19]])

In [115]:
demo_array.shape

(15, 1)

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [118]:
type(arr)

numpy.ndarray

In [119]:
arr.max()

24

In [120]:
arr.min()

0

In [121]:
arr.argmax() # index of max elem

24

In [122]:
arr.argmin()

0

In [137]:

np.random.seed(10)
mat = np.random.randint(1,5,(2,3))
print(mat)
print(mat.argmax()) # it will flatten it as a row major 1D vec and give the index of max. 


[[2 2 1]
 [4 1 2]]
3


In [138]:
mat[1]

array([4, 1, 2])

In [139]:
import numpy as np

np.random.seed(10)
mat = np.random.randint(1,5,(2,3))
print("Matrix:\n", mat)

# Get the index of the max element in 1D flattened form
max_index = mat.argmax()

# Convert to 2D (row, col) index
row, col = np.unravel_index(max_index, mat.shape)
print("Max element is at row:", row, "column:", col)


Matrix:
 [[2 2 1]
 [4 1 2]]
Max element is at row: 1 column: 0
