In [17]:
import numpy as np


In [18]:
arr = np.arange(11,89,6)

In [19]:
print(arr)

[11 17 23 29 35 41 47 53 59 65 71 77 83]


In [20]:
arr[0]

11

In [21]:
arr[-1]

83

In [22]:
arr[:]

array([11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83])

In [23]:
arr[:-1]

array([11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77])

In [24]:
arr[0:-1]

array([11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77])

In [25]:
arr[::][::-1]

array([83, 77, 71, 65, 59, 53, 47, 41, 35, 29, 23, 17, 11])

In [26]:
arr[1:3]

array([17, 23])

In [27]:
arr[:3]

array([11, 17, 23])

#### Broadcasting:

In [28]:
arr

array([11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83])

In [29]:
#arr[0:5] = 100

In [30]:
arr

array([11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83])

In [32]:
slice_of_arr = arr[0:5] 
print(slice_of_arr)

[11 17 23 29 35]


In [33]:
slice_of_arr[:]= 99

In [34]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [37]:
arr # change happens in the original array(it is not copied**** ), since it shares same memory

array([99, 99, 99, 99, 99, 41, 47, 53, 59, 65, 71, 77, 83])

In [44]:
demo_list = list(np.arange(12,78,6))

In [45]:
demo_list

[12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72]

In [46]:
slice_ofdemo_lst = demo_list[0:5]

In [48]:
# slice_ofdemo_lst[:] = 90 # it wont work.

In [49]:
slice_ofdemo_lst

[12, 18, 24, 30, 36]

In [50]:
slice_ofdemo_lst[0] = 10

In [51]:
demo_list

[12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72]

In [52]:
#In list it wont alters. 
#but while using array it alters the original array if u are not copying it. 

In [53]:
import numpy as np

parent = np.array([1, 2, 3])
child = parent.copy()   # deep copy, independent of parent

child[0] = 100

print("Parent:", parent)  # Output: [1 2 3]
print("Child: ", child)   # Output: [100 2 3]


Parent: [1 2 3]
Child:  [100   2   3]


In [55]:
import numpy as np

arr = np.arange(10)

# First slice, then make a copy
arr_slice = arr[1:4].copy()  

# Modify the slice
arr_slice = arr_slice + 100

print("Original array:", arr)      # unchanged
print("Modified slice:", arr_slice)


Original array: [0 1 2 3 4 5 6 7 8 9]
Modified slice: [101 102 103]


####  Indexing and slicing in 2D matrix.

In [56]:
list_2d = [[1,2,3],[4,5,6],[2,5,7]]

In [58]:
list_2d[1][2]

6

In [59]:
demo_arr = np.array(list_2d)

In [64]:
demo_arr

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 7]])

In [65]:
demo_arr[0]

array([1, 2, 3])

In [66]:
demo_arr[1][1]

5

In [67]:
demo_arr[-1][-1]

7

In [79]:
demo_arr[0][0]
demo_arr[1][0]
demo_arr[2][0]

2

In [81]:
first_col = demo_arr[:, 0]
print(first_col)


[1 4 2]


In [82]:
np.random.seed(90)
arr_2 = np.random.randint(1,100,(7,6))

In [83]:
print(arr_2)

[[92 30 32 68 40 69]
 [59 38 19 75 97 52]
 [31 81 19 78 83 10]
 [ 1  1 11 96 13  5]
 [27 10 49 71 76 81]
 [80 31 98 15 32 67]
 [ 3 41 88 29 67 49]]


In [84]:
arr_2[0,1]

30

In [85]:
arr_2[-7,-5]

30

In [86]:
arr_2.shape

(7, 6)

#### slicing: 


In [88]:
arr_2[1:4,:]

array([[59, 38, 19, 75, 97, 52],
       [31, 81, 19, 78, 83, 10],
       [ 1,  1, 11, 96, 13,  5]])

In [91]:
arr_2[1:4,-3:-2]

array([[75],
       [78],
       [96]])

In [94]:
arr_2[:4]

array([[92, 30, 32, 68, 40, 69],
       [59, 38, 19, 75, 97, 52],
       [31, 81, 19, 78, 83, 10],
       [ 1,  1, 11, 96, 13,  5]])

In [96]:
arr_2[:,4]

array([40, 97, 83, 13, 76, 32, 67])

#### Conditional selection:

In [98]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
boolean_arr = arr < 4
boolean_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [104]:
arr[boolean_arr == True]

array([0, 1, 2, 3])

In [105]:
arr[boolean_arr == False]

array([4, 5, 6, 7, 8, 9])

In [106]:
arr[boolean_arr ]

array([0, 1, 2, 3])

In [109]:
arr[arr < 4 ]

array([0, 1, 2, 3])

In [110]:
arr[arr != 4]

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [111]:
arr[arr%2 ==0]

array([0, 2, 4, 6, 8])