In [1]:
import numpy as np 

In [7]:
arr = np.arange(10)

In [8]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr + arr 
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
arr // 4

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2])

In [12]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

### Universal Array Functions:
* ufunc

In [13]:
# square root 
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
# exponential 
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [15]:
# sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
# natural log 
np.log(arr)

/tmp/ipykernel_789003/2149934815.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
np.deg2rad(np.array([0,30,60,90,120,180]))

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       3.14159265])

#### Summary statisctis:


In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr.max()

9

In [22]:
arr.mean()

4.5

In [23]:
arr.std()

2.8722813232690143

In [24]:
arr.min()

0

In [25]:
arr.prod()

0

#### Access logic: 

* axis 0 ---->  (rowwise )
* axis 1-----> ( coloumnwise)


In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr6= arr.reshape(2,5)

In [40]:
arr6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
arr6.sum()

45

In [42]:
arr6.sum(axis = 0)

array([ 5,  7,  9, 11, 13])

In [43]:
arr6.sum(axis = 1)

array([10, 35])

In [44]:
arr6.var(axis = 1)

array([2., 2.])

In [51]:
np.random.seed(10)
arr_7= np.random.randint(1,100,(5,4))

In [52]:
arr_7

array([[10, 16, 65, 29],
       [90, 94, 30,  9],
       [74,  1, 41, 37],
       [17, 12, 55, 89],
       [63, 34, 73, 79]])

In [53]:
arr_7.sum(axis = 1)

array([120, 223, 153, 173, 249])

In [54]:
arr_7.sum(axis = 0)

array([254, 157, 264, 243])

In [55]:
arr_7.var(axis = 0)

array([1006.16, 1092.64,  244.16,  928.64])

In [56]:
arr_7.mean(axis = 0)

array([50.8, 31.4, 52.8, 48.6])